export const chars: string[] = [
      "Zhu Yuan",
      "Ellen",
      "Grace",
      "Rina",
      "Koleda",
      "Nekomata",
      "Soldier 11",
      "Lycaon",
      "Anby",
      "Nicole",
      "Corine",
      "Billy",
      "Anton",
      "Ben",
      "Soukaku",
      "Lucy",
      "Piper",
  ];
export const specialties: Record<string, string> = {
    "Zhu Yuan": "Attack",
    "Ellen": "Attack",
    "Grace": "Anomaly",
    "Rina": "Support",
    "Koleda": "Stun",
    "Nekomata": "Attack",
    "Soldier 11": "Attack",
    "Lycaon": "Stun",
    "Anby": "Stun",
    "Nicole": "Support",
    "Corine": "Attack",
    "Billy": "Attack",
    "Anton": "Attack",
    "Ben": "Defense",
    "Soukaku": "Support",
    "Lucy": "Support",
    "Piper": "Anomaly",
  };
export const elements: Record<string, string> = {
    "Zhu Yuan": "Ether",
    "Ellen": "Ice",
    "Grace": "Electric",
    "Rina": "Electric",
    "Koleda": "Fire",
    "Nekomata": "Physical",
    "Soldier 11": "Fire",
    "Lycaon": "Ice",
    "Anby": "Electric",
    "Nicole": "Ether",
    "Corine": "Physical",
    "Billy": "Physical",
    "Anton": "Electric",
    "Ben": "Fire",
    "Soukaku": "Ice",
    "Lucy": "Fire",
    "Piper": "Physical",
  };
export const parties: string[][] = [
    ["Zhu Yuan", "Grace", "Nicole"],
    ["Zhu Yuan", "Rina", "Nicole"],
    ["Zhu Yuan", "Koleda", "Rina"],
    ["Zhu Yuan", "Koleda", "Nicole"],
    ["Zhu Yuan", "Koleda", "Lucy"],
    ["Zhu Yuan", "Lycaon", "Rina"],
    ["Zhu Yuan", "Lycaon", "Nicole"],
    ["Zhu Yuan", "Lycaon", "Soukaku"],
    ["Zhu Yuan", "Anby", "Rina"],
    ["Zhu Yuan", "Anby", "Nicole"],
    ["Zhu Yuan", "Nicole", "Lucy"],
    ["Zhu Yuan", "Billy", "Nicole"],
    ["Zhu Yuan", "Piper", "Nicole"],
    ["Ellen", "Grace", "Soukaku"],
    ["Ellen", "Koleda", "Rina"],
    ["Ellen", "Koleda", "Soukaku"],
    ["Ellen", "Lycaon", "Rina"],
    ["Ellen", "Lycaon", "Soukaku"],
    ["Ellen", "Anby", "Rina"],
    ["Ellen", "Anby", "Soukaku"],
    ["Ellen", "Corine", "Soukaku"],
    ["Ellen", "Corine", "Lucy"],
    ["Ellen", "Ben", "Soukaku"],
    ["Ellen", "Soukaku", "Rina"],
    ["Ellen", "Soukaku", "Nicole"],
    ["Ellen", "Soukaku", "Lucy"],
    ["Ellen", "Piper", "Soukaku"],
    ["Grace", "Rina", "Nicole"],
    ["Grace", "Rina", "Lucy"],
    ["Grace", "Koleda", "Rina"],
    ["Grace", "Koleda", "Lucy"],
    ["Grace", "Anby", "Rina"],
    ["Grace", "Nicole", "Lucy"],
    ["Grace", "Ben", "Lucy"],
    ["Nekomata", "Grace", "Nicole"],
    ["Nekomata", "Anby", "Nicole"],
    ["Nekomata", "Piper", "Grace"],
    ["Nekomata", "Piper", "Nicole"],
    ["Nekomata", "Piper", "Lucy"],
    ["Soldier 11", "Koleda", "Nicole"],
    ["Soldier 11", "Koleda", "Ben"],
    ["Soldier 11", "Koleda", "Lucy"],
    ["Soldier 11", "Lycaon", "Lucy"],
    ["Soldier 11", "Nicole", "Lucy"],
    ["Soldier 11", "Ben", "Nicole"],
    ["Soldier 11", "Ben", "Lucy"],
    ["Soldier 11", "Piper", "Lucy"],
    ["Lycaon", "Soukaku", "Nicole"],
    ["Corine", "Lycaon", "Soukaku"],
    ["Corine", "Piper", "Lucy"],
    ["Anton", "Grace", "Rina"],
    ["Anton", "Grace", "Anby"],
    ["Anton", "Grace", "Ben"],
    ["Anton", "Grace", "Lucy"],
    ["Anton", "Koleda", "Ben"],
    ["Anton", "Anby", "Rina"],
    ["Anton", "Anby", "Nicole"],
    ["Anton", "Anby", "Lucy"],
    ["Anton", "Piper", "Grace"],
    ["Piper", "Grace", "Koleda"],
    ["Piper", "Grace", "Rina"],
    ["Piper", "Grace", "Anby"],
    ["Piper", "Grace", "Lucy"],
    ["Piper", "Koleda", "Lucy"],
];